language: python

env:
  - BROWSER=Chrome
  - BROWSER=PhantomJS
  - BROWSER=Firefox

install:
  # Install Chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb
  - if [ x$BROWSER == xChrome ]; then sudo dpkg --install google-chrome-stable_current_amd64.deb || sudo apt-get -f install; ls -l /usr/bin/google-chrome; fi
  # Install PIL
  - pip install -r .requirements --use-mirrors

script:
  - python run-tests.py -a -x -b $BROWSER

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true
