language: python

env:
  - BROWSER=Chrome
  - BROWSER=PhantomJS
  - BROWSER=Firefox

install:
  - ./.travis-setup.sh

script:
  - python run-tests.py -a -x -b $BROWSER

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true
