language: python

env:
  - BROWSER=Chrome
  - BROWSER=PhantomJS
  - BROWSER=Firefox

install:
  # Install Chrome
  - export CHROME=google-chrome-stable_current_amd64.deb; wget https://dl.google.com/linux/direct/$CHROME; if [ x$BROWSER == xChrome ]; then sudo dpkg --install $CHROME || sudo apt-get -f install; ls -l /usr/bin/google-chrome; fi
  # Install PIL
  - pip install -r .requirements --use-mirrors

script:
  - python run-tests.py -a -x -b $BROWSER

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true
